//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ors.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ors.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 模块开始销毁 的本地化字符串。
        /// </summary>
        internal static string Module_Begin_Finalize {
            get {
                return ResourceManager.GetString("Module_Begin_Finalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块开始初始化 的本地化字符串。
        /// </summary>
        internal static string Module_Begin_Initialize {
            get {
                return ResourceManager.GetString("Module_Begin_Initialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块结束销毁 的本地化字符串。
        /// </summary>
        internal static string Module_End_Finalize {
            get {
                return ResourceManager.GetString("Module_End_Finalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块结束初始化 的本地化字符串。
        /// </summary>
        internal static string Module_End_Initialize {
            get {
                return ResourceManager.GetString("Module_End_Initialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块{0}在销毁中发生错误 的本地化字符串。
        /// </summary>
        internal static string Module_Has_Error_While_Finalizing {
            get {
                return ResourceManager.GetString("Module_Has_Error_While_Finalizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块管理器开始销毁 的本地化字符串。
        /// </summary>
        internal static string Modules_Begin_Finalization {
            get {
                return ResourceManager.GetString("Modules_Begin_Finalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块管理器开始初始化 的本地化字符串。
        /// </summary>
        internal static string Modules_Begin_Intialization {
            get {
                return ResourceManager.GetString("Modules_Begin_Intialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块管理器结束销毁 的本地化字符串。
        /// </summary>
        internal static string Modules_End_Finalization {
            get {
                return ResourceManager.GetString("Modules_End_Finalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块管理器结束初始化 的本地化字符串。
        /// </summary>
        internal static string Modules_End_Intialization {
            get {
                return ResourceManager.GetString("Modules_End_Intialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不能为空。 的本地化字符串。
        /// </summary>
        internal static string RuleViolated_ArgumentNull {
            get {
                return ResourceManager.GetString("RuleViolated_ArgumentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}已经存在。 的本地化字符串。
        /// </summary>
        internal static string RuleViolated_Duplicated {
            get {
                return ResourceManager.GetString("RuleViolated_Duplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}长度超出范围（{1}到{2}之间）。 的本地化字符串。
        /// </summary>
        internal static string RuleViolated_LengthOutOfRange {
            get {
                return ResourceManager.GetString("RuleViolated_LengthOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身份未认证。 的本地化字符串。
        /// </summary>
        internal static string RuleViolated_NotAuthenticated {
            get {
                return ResourceManager.GetString("RuleViolated_NotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}没有操作权限。 的本地化字符串。
        /// </summary>
        internal static string RuleViolated_NotAuthorized {
            get {
                return ResourceManager.GetString("RuleViolated_NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不支持。 的本地化字符串。
        /// </summary>
        internal static string RuleViolated_NotSupported {
            get {
                return ResourceManager.GetString("RuleViolated_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}未找到。 的本地化字符串。
        /// </summary>
        internal static string RuleViolated_ObjectNotFound {
            get {
                return ResourceManager.GetString("RuleViolated_ObjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}的值超出范围（{1}到{2}之间）。 的本地化字符串。
        /// </summary>
        internal static string RuleViolated_OutOfRange {
            get {
                return ResourceManager.GetString("RuleViolated_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知错误。 的本地化字符串。
        /// </summary>
        internal static string RuleViolated_Unknown {
            get {
                return ResourceManager.GetString("RuleViolated_Unknown", resourceCulture);
            }
        }
    }
}
